services:
  - type: web
    name: central-altitude-api
    runtime: node
    rootDir: api
    buildCommand: npm install && npx prisma generate && npm run build && npx prisma db seed
    startCommand: npx prisma migrate deploy && node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dgowmqdkk
      - key: CLOUDINARY_API_KEY
        value: "352979691142268"
      - key: CLOUDINARY_API_SECRET
        sync: false
