-- Add extended RDO fields (GeoControl model)
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "numero" TEXT;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "endereco" TEXT;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "responsavel" TEXT;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "turnoManha" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "turnoTarde" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "turnoNoite" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "moi" JSONB;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "mod" JSONB;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "equipamentos" JSONB;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "tarefas" JSONB;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "ocorrencias" JSONB;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "obs" TEXT;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "rdoStatus" TEXT NOT NULL DEFAULT 'rascunho';
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "assinaturaEngNome" TEXT;
ALTER TABLE "rdos" ADD COLUMN IF NOT EXISTS "assinaturaEngData" TEXT;
